version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/Twitter

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
        path: ~/repo
      - run: mvn dependency:go-offline
      - run: mvn -B -DskipTests clean package
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/Twitter

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
        path: ~/repo
      - run: mvn dependency:go-offline
      - run: mvn clean package
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


      