version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: cd Twitter
      - run: RUN mvn -B -DskipTests clean package
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/Twitter

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean package
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test


      